# Generated by Django 5.2.14 on 2026-05-28 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#000000', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='scheduled_date',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='followup',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='note',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('ON_HOLD', 'On hold'), ('CONVERTED', 'Converted'), ('ON_TRIP', 'On trip'), ('PAST_TRIP', 'Past trips'), ('CANCELLED', 'Cancelled'), ('DROPPED', 'Dropped'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='trips', to='crm.tag'),
        ),
    ]
