# Generated by Django 5.2.14 on 2026-05-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_tag_rename_scheduled_date_followup_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlead',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_leads', to='crm.trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='children_ages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='no_of_adults',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='trip',
            name='no_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='no_of_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='salutation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_foc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
