# Generated by Django 5.2.14 on 2026-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rawlead_trip_trip_children_ages_trip_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SEEN', 'Seen'), ('DONE', 'Done')], default='NEW', max_length=10),
        ),
    ]
