# Generated by Django 5.2.14 on 2026-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rawlead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlead',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawlead',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawlead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rawlead',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawlead',
            name='no_of_adults',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rawlead',
            name='no_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawlead',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawlead',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
