# Generated by Django 5.2.14 on 2026-05-28 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rawlead_contact_name_rawlead_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=500)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='crm.quote')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
