# Generated by Django 5.2.14 on 2026-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_itineraryday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='India', max_length=255)),
                ('iso2', models.CharField(blank=True, max_length=5)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='crm_destina_city_7a7fd6_idx'), models.Index(fields=['state'], name='crm_destina_state_85d36d_idx')],
            },
        ),
    ]
