# Generated by Django 5.2.14 on 2026-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelitem',
            name='aweb',
            field=models.PositiveIntegerField(default=0, help_text='Adults with extra bed'),
        ),
        migrations.AddField(
            model_name='hotelitem',
            name='cnb',
            field=models.PositiveIntegerField(default=0, help_text='Children no bed'),
        ),
        migrations.AddField(
            model_name='hotelitem',
            name='comp_child_max_age',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hotelitem',
            name='cweb',
            field=models.PositiveIntegerField(default=0, help_text='Children with extra bed'),
        ),
        migrations.AddField(
            model_name='hotelitem',
            name='given_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotelitem',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotelitem',
            name='meal_plan',
            field=models.CharField(choices=[('CP', 'CP - Continental Plan'), ('MAP', 'MAP - Modified American Plan'), ('AP', 'AP - American Plan'), ('EP', 'EP - European Plan'), ('BB', 'BB - Bed & Breakfast')], default='CP', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelitem',
            name='pax_per_room',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hotelitem',
            name='star_rating',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quote',
            name='agent_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='internal_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='internal_price_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='pricing_strategy',
            field=models.CharField(choices=[('overall', 'Overall'), ('per_person', 'Per-Person')], default='overall', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='remarks_for_customer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='round_to',
            field=models.PositiveIntegerField(default=5, help_text='Round selling price to nearest N'),
        ),
        migrations.AddField(
            model_name='quote',
            name='selling_currency',
            field=models.CharField(default='INR', max_length=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_applied_on',
            field=models.CharField(default='Cost+Markup', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_foc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportitem',
            name='cab_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transportitem',
            name='duration_mins',
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='transportitem',
            name='service_locations',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='transportitem',
            name='service_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transportitem',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transportitem',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transportitem',
            name='transport_type',
            field=models.CharField(choices=[('FLIGHT', 'Flight'), ('CAB', 'Cab/Transfer'), ('ACTIVITY', 'Activity/Sightseeing'), ('TRAIN', 'Train')], default='CAB', max_length=20),
        ),
    ]
