# Generated by Django 5.2.14 on 2026-05-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_hotelitem_aweb_hotelitem_cnb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlead',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SEEN', 'In Progress'), ('DONE', 'Done'), ('ARCHIVED', 'Archived')], default='NEW', max_length=10),
        ),
    ]
